[default]
APP_NAME = 'AssetManagementService'
DB_MIN_CONN = 5
DB_MAX_CONN = 20
DB_RECYCLE_SECONDS = 300
DB_STALE_TIMEOUT_SECONDS = 300
SCHEDULER_CRON_HOUR = 10
RECREATE_TABLES = false
TXN_EXPIRED_SECONDS = 300
AMS_DECIMAL = "DECIMAL(23,7)"

[development]
DB_NAME = 'amx'
DB_HOST = '127.0.0.1'
DB_PORT = 3306
DB_USER = 'root'
DB_PASSWD = 'liurusi321'
ACCOUNT_SECRET_AES_KEY = 'secrets/key'
ACCOUNT_SECRET_AES_IV = 'secrets/iv'

[pdxdev]
DB_NAME = 'amx'
DB_HOST = '10.80.5.236'
DB_PORT = 3306
DB_USER = 'root'
DB_PASSWD = 'gjZl6qzF760HUX1KjZpRZJfbV'
ACCOUNT_SECRET_AES_KEY = '/run/secrets/ams_account_secret_key'
ACCOUNT_SECRET_AES_IV = '/run/secrets/ams_account_secret_iv'

[production]
DB_NAME = 'amx'
DB_HOST = '10.80.5.236'
DB_PORT = 3306
DB_USER = 'root'
DB_PASSWD = 'gjZl6qzF760HUX1KjZpRZJfbV'
ACCOUNT_SECRET_AES_KEY = '/run/secrets/ams_account_secret_key'
ACCOUNT_SECRET_AES_IV = '/run/secrets/ams_account_secret_iv'
